### ISSUE TITLE
背景是黑的

### ISSUE THREAD

**Issue by panpf** [Simon-Leeeeeeeee/SLWidget#1]
如题，按照文档集成后运行页面背景是黑色的，需要在 onContentChanged 的时候更改 SwibackView 的背景色，如下：
```java
    @Override
    public void onContentChanged() {
        super.onContentChanged();

        if (mSwipeBackHelper != null) {
            ViewGroup viewGroup = mSwipeBackHelper.getSwipeBackView((ViewGroup) getWindow().getDecorView());
            viewGroup.setBackgroundColor(getResources().getColor(R.color.windowBackground));
        }
    }
```

同时 mSwipeBackHelper 的初始化必须在 setContentView 之前

**Comment by Simon-Leeeeeeeee** [comment]
@panpf 你说的黑色背景是指你的activity的背景是黑色吗？因为没有侧滑时窗口是不透明的，如果你没有给你的activity布局指定背景色，必然是黑色的。而且滑动时会变为透明。你需要在你layout的根View下指定android:background即可。

**Comment by Simon-Leeeeeeeee** [comment]
@panpf 请问问题解决了吗？问题我先关闭了，如果仍有疑问，请Reopen
