### ISSUE TITLE
输入法问题

### ISSUE THREAD

**Issue by panpf** [Simon-Leeeeeeeee/SLWidget#2]
当输入框在页面底部，弹起输入法后输入框需要显示在输入法顶部的时候，输入框和输入法之间会有一大段空白

**Comment by Simon-Leeeeeeeee** [comment]
@panpf 一大段空白是否和输入法等高？demo运行有这种现象吗？如果有，麻烦提供一下问题机型，我测试一下

**Comment by Simon-Leeeeeeeee** [comment]
@panpf 你好，请问可以提供一下反馈信息吗？据我推测可能是输入法未设置adjustResize导致。问题我先关闭了，如果有疑问请Reopen
